# 开发环境配置文件
# 注意：这是开发环境配置，生产环境请使用 application-prod.yml

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: enterprise-mail-system
    
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/mail_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: ${JPA_FORMAT_SQL:false}
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DB:0}
    timeout: 10000ms
    lettuce:
      pool:
        max-active: ${REDIS_MAX_ACTIVE:8}
        max-idle: ${REDIS_MAX_IDLE:8}
        min-idle: ${REDIS_MIN_IDLE:0}
        max-wait: ${REDIS_MAX_WAIT:-1ms}
  
  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_TTL:3600000}
      cache-null-values: false
      enable-statistics: true
        
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:admin@enterprise.mail}
    password: ${MAIL_PASSWORD:Admin@Secure2024!}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
          ssl:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
            
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:25MB}
      max-request-size: ${MAX_REQUEST_SIZE:30MB}
      enabled: true
      
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: ${TIMEZONE:GMT+8}
    serialization:
      write-dates-as-timestamps: false
      
# JWT Configuration - MUST be changed in production
jwt:
  secret: ${JWT_SECRET:CHANGE_THIS_SECRET_KEY_IN_PRODUCTION_USE_STRONG_RANDOM_STRING_AT_LEAST_256_BITS}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
  
# Mail Server Configuration
mail-server:
  smtp:
    enabled: ${SMTP_ENABLED:true}
    port: ${SMTP_PORT:25}
    secure-port: ${SMTP_SSL_PORT:465}
    ssl-port: ${SMTP_SSL_PORT:465}
    max-connections: ${SMTP_MAX_CONN:100}
    auth-required: true
    tls-enabled: true
    
  imap:
    enabled: ${IMAP_ENABLED:true}
    port: ${IMAP_PORT:143}
    secure-port: ${IMAP_SSL_PORT:993}
    ssl-port: ${IMAP_SSL_PORT:993}
    max-connections: ${IMAP_MAX_CONN:50}
    
  pop3:
    enabled: ${POP3_ENABLED:true}
    port: ${POP3_PORT:110}
    secure-port: ${POP3_SSL_PORT:995}
    ssl-port: ${POP3_SSL_PORT:995}
    max-connections: ${POP3_MAX_CONN:30}
    
  domain:
    default: ${MAIL_DOMAIN:enterprise.mail}
    allowed-domains:
      - ${MAIL_DOMAIN:enterprise.mail}
      - ${ALLOWED_DOMAIN_2:company.com}
      
  storage:
    path: ${MAIL_STORAGE_PATH:/var/mail/storage}
    max-mailbox-size: ${MAX_MAILBOX_SIZE:1073741824} # 1GB
    max-message-size: ${MAX_MESSAGE_SIZE:26214400} # 25MB
    
  security:
    dkim-enabled: ${DKIM_ENABLED:false}
    spf-enabled: ${SPF_ENABLED:false}
    dmarc-enabled: ${DMARC_ENABLED:false}
    spam-filter-enabled: ${SPAM_FILTER_ENABLED:false}
    virus-scan-enabled: ${VIRUS_SCAN_ENABLED:false}
    rate-limit-enabled: ${RATE_LIMIT_ENABLED:true}
    max-requests-per-minute: ${RATE_LIMIT:60}
    
# Logging Configuration
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.enterprise.mail: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
    org.hibernate: ${LOG_LEVEL_HIBERNATE:WARN}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_PATH:logs}/mail-system.log
    max-size: 10MB
    max-history: 30
    
# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  metrics:
    export:
      prometheus:
        enabled: false
        
# API Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${API_DOCS_ENABLED:true}
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SWAGGER_ENABLED:true}
    
# CORS Configuration
cors:
  allowed-origins:
    - ${CORS_ORIGIN_1:http://localhost:3000}
    - ${CORS_ORIGIN_2:http://localhost:5173}
    - ${CORS_ORIGIN_3:http://localhost:8081}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Content-Type
    - X-Requested-With
    - Accept
    - Origin
  exposed-headers:
    - Authorization
    - Content-Type
  allow-credentials: true
  max-age: 3600

# Security Configuration
security:
  require-https: ${REQUIRE_HTTPS:false}
  session-timeout: ${SESSION_TIMEOUT:1800}
  max-login-attempts: ${MAX_LOGIN_ATTEMPTS:5}
  lockout-duration: ${LOCKOUT_DURATION:900}
  password-min-length: 8
  password-require-uppercase: true
  password-require-lowercase: true
  password-require-digit: true
  password-require-special: true