# 开发环境配置
spring:
  profiles:
    active: dev
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    
  datasource:
    url: jdbc:mysql://localhost:3306/mail_system_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root123456}
    
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD:}
    
logging:
  level:
    root: INFO
    com.enterprise.mail: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
# 开发环境特定配置
debug: true
api-docs:
  enabled: true
  
# JWT配置
jwt:
  secret: ${JWT_SECRET:dev-secret-key-for-jwt-2024}
  expiration: 86400
  
# 邮件服务器配置（开发环境）
mail:
  server:
    enabled: true
    smtp:
      host: 0.0.0.0
      port: 2525
    imap:
      host: 0.0.0.0
      port: 1143
    pop3:
      host: 0.0.0.0
      port: 1110
      
# CORS配置（开发环境）
cors:
  allowed-origins: http://localhost:5173,http://localhost:3000,http://localhost:8080
  
# 文件上传配置
spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 50MB
  
# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always